name: MLOps Pipeline - Test, Train, Inference

on:
  push:
    branches:
      - inference_branch

jobs:
  test_cases_job:
    name: Run Test Cases
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run Pytest suite
      run: pytest tests/

  train_job:
    name: Train Model
    runs-on: ubuntu-latest
    needs: test_cases_job # This job depends on test_cases_job
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run training script
      run: python -m src.train

    - name: Upload trained model artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model_train.pkl

  inference_job:
    name: Run Inference
    runs-on: ubuntu-latest
    needs: train_job # This job depends on train_job
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Download trained model artifact
      uses: actions/download-artifact@v4
      with:
        name: trained-model
        path: . # Download to the current directory

    - name: Run inference script
      run: python -m src.inference